# Generated by Django 4.0.1 on 2022-01-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
