# Generated by Django 4.0.1 on 2022-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_jobseeker_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
