# Generated by Django 4.0.1 on 2022-01-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_jobseeker_user_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='user_file',
            new_name='user_resume',
        ),
    ]
