# Generated by Django 4.0.1 on 2022-01-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_user_file_jobseeker_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='recent_job',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
