# Generated by Django 4.0.1 on 2022-01-29 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_company_company_description_company_user_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='user_image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='SeekerSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
