# Generated by Django 4.0.1 on 2022-01-29 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_jobseeker_user_image_seekerskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerskills',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobseeker'),
        ),
    ]
