# Generated by Django 4.0.1 on 2022-01-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_seekerskills_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seekerskills',
            name='skill_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
