# Generated by Django 4.0.1 on 2022-01-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_company_location_alter_seekerskills_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user_image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='images'),
        ),
    ]
