# Generated by Django 4.0.1 on 2022-01-31 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_company_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
    ]
