# Generated by Django 4.0.1 on 2022-01-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
