# Generated by Django 4.0.1 on 2022-02-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_jobs_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
