# Generated by Django 4.0.1 on 2022-02-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_jobapplication_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerPreviousWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('yearStarted', models.IntegerField()),
                ('yearEnded', models.IntegerField()),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobseeker')),
            ],
        ),
    ]
