# Generated by Django 4.0.1 on 2022-02-07 02:53

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_seekerpreviouswork_yearended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerpreviouswork',
            name='yearStarted',
            field=models.PositiveIntegerField(default=1999, validators=[django.core.validators.MinValueValidator(1984), base.models.max_value_current_year]),
        ),
    ]
