# Generated by Django 4.0.1 on 2022-02-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_seekerpreviouswork_yearstarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
