# Generated by Django 4.0.1 on 2022-02-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_activitylogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogs',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
