# Generated by Django 4.0.2 on 2022-02-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_activitylogs_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='qualification',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
